---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:

     data_center_name: CoolDataCenter
     compatibility_version: 4.2

     clusters:
      - name: TrustedCluster
        cpu_type: Intel Conroe Family
        memory_policy: server
        ha_reservation: true

     hosts:
      - name: kvm1.example.com
        address: kvm1.example.com
        cluster: TrustedCluster
        password: r3dh4t1!
      - name: kvm2.example.com
        address: kvm2.example.com
        cluster: TrustedCluster
        password: r3dh4t1!

     storages:
       VMStorageNFS:
         master: true
         state: present
         nfs:
           address: storage.example.com
           path: /exports/vms
       ISO:
         domain_function: iso
         state: present
         nfs:
           address: storage.example.com
           path: /exports/isos
       Export:
         domain_function: export
         state: present
         nfs:
           address: storage.example.com
           path: /exports/export

     logical_networks:
      - name: vlan100
        vlan_tag: 100
        clusters:
          - name: TrustedCluster
            assigned: yes
            required: no
            display: no
            migration: no
            gluster: no
            
     host_networks:
      - name: kvm1.example.com
        check: true
        save: true
        interface: eth0
        networks:
          - name: vlan100
      - name: kvm2.example.com
        check: true
        save: true
        interface: eth0
        networks:
          - name: vlan100

  pre_tasks:
  - name: Login to oVirt
    ovirt_auth:
      insecure: "{{ engine_insecure | default(true) }}"
    tags:
      - always

  roles:
    - ovirt.infra
